<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>UnifiMcp.Tests</_Parameter1>
    </AssemblyAttribute>
    <ProjectReference Include="..\Unifi.Mcp.Client\Unifi.Mcp.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ApiContracts\*.json" />
  </ItemGroup>

</Project>
